//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportSchool111.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetingTeams
    {
        public int team_id { get; set; }
        public Nullable<int> competition_id { get; set; }
        public Nullable<int> school_id { get; set; }
        public string team_name { get; set; }
    
        public virtual Schools Schools { get; set; }
    }
}
