//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportSchool111.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competitions()
        {
            this.CompetingTeams = new HashSet<CompetingTeams>();
            this.Results = new HashSet<Results>();
        }
    
        public int competition_id { get; set; }
        public string competition_name { get; set; }
        public Nullable<System.DateTime> competition_date { get; set; }
        public Nullable<int> section_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetingTeams> CompetingTeams { get; set; }
        public virtual Sections Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
